# VIBRATION message data
# @description: Vibration levels and accelerometer clipping

Header header

float32 vibration_x		# Vibration levels on X-axis
float32 vibration_y		# Vibration levels on Y-axis
float32 vibration_z		# Vibration levels on Z-axis
uint32 clipping_0		# 1st accelerometer clipping count
uint32 clipping_1		# 2nd accelerometer clipping count
uint32 clipping_2		# 3rd accelerometer clipping count