"""
SRTM continent lookup table.

Maps each 1-degree tile to its continent directory on terrain.ardupilot.org.
The raw 116x360 byte grid is stored in ``srtm_continent_map.bin`` next to
this module.  Each byte is a continent index (0-5) or 0xFF for no data.

Generated by tools/generate_srtm_continent_map.py -- DO NOT EDIT.
"""

from __future__ import annotations

try:
    from importlib.resources import files  # nosemgrep: python37-compatibility-importlib2
except ImportError:
    # Python < 3.9 fallback (Humble uses 3.10+, but be defensive)
    from importlib_resources import files  # type: ignore[no-redef]

_CONTINENTS = (
    'Africa/',
    'Australia/',
    'Eurasia/',
    'Islands/',
    'North_America/',
    'South_America/',
)

_LAT_MIN = -56
_LAT_RANGE = 116
_LON_MIN = -180
_LON_RANGE = 360
_NO_DATA = 0xFF

_MAP: bytes = (files(__package__) / 'srtm_continent_map.bin').read_bytes()
assert len(_MAP) == _LAT_RANGE * _LON_RANGE, (
    f'srtm_continent_map.bin size mismatch: {len(_MAP)} != {_LAT_RANGE * _LON_RANGE}'
)


def lookup_continent(lat: int, lon: int) -> str | None:
    """Return the continent directory for a 1-degree tile, or None if unavailable."""
    li = lat - _LAT_MIN
    lo = lon - _LON_MIN
    if not (0 <= li < _LAT_RANGE and 0 <= lo < _LON_RANGE):
        return None
    idx = _MAP[li * _LON_RANGE + lo]
    if idx == _NO_DATA:
        return None
    return _CONTINENTS[idx]
