[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mavros"
version = "2.12.0"
description = "Helper scripts and module for MAVROS"
license = "Triple licensed under GPLv3, LGPLv3 and BSD"
authors = [
    {name = "Vladimir Ermakov", email = "vooon341@gmail.com"},
]
maintainers = [
    {name = "Vladimir Ermakov", email = "vooon341@gmail.com"},
]
keywords = ["ROS"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Topic :: Software Development",
]
requires-python = ">=3.10"

[project.scripts]
mav = "mavros.cmd:cli"

[tool.setuptools.packages.find]
include = ["mavros", "mavros.*"]

[tool.ruff]
line-length = 99

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.pycodestyle]
max-line-length = 99
