[options.entry_points]
console_scripts =
    mav=mavros.cmd:cli

[develop]
script_dir=$base/lib/mavros

[install]
install_scripts=$base/lib/mavros

[flake8]
# NOTE: based on ament_flake8.ini from Jazzy, but extended with A005,CNL100,Q000,I100,I101
extend-ignore = A005,B902,C816,CNL100,D100,D101,D102,D103,D104,D105,D106,D107,D203,D212,D404,I202,Q000,I100,I101
import-order-style = google
max-line-length = 99
show-source = true
statistics = true
