# Type for controlling onboard camera triggering system

bool    trigger_enable		# Trigger enable/disable
bool    sequence_reset		# Reset the trigger sequence
bool    trigger_pause		# Pause triggering, but without switching the camera off or retracting it.
---
bool success
uint8 result
