# MAVLink command: MAV_CMD_REQUEST_MESSAGE
# https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_MESSAGE
# Specifically used to request Information messages from Gimbal Device and Gimbal Manager
# https://mavlink.io/en/messages/common.html#GIMBAL_MANAGER_INFORMATION
# https://mavlink.io/en/messages/common.html#GIMBAL_DEVICE_INFORMATION

---
bool success
# raw result returned by COMMAND_ACK
uint8 result