#!/usr/bin/python3

if False:
    import sys

    from pkg_resources import load_entry_point

    if __name__ == '__main__':
        sys.exit(load_entry_point('mavros', 'console_scripts', 'mav')())

else:
    from mavros.cmd import cli

    cli()
