#!/usr/bin/env bash
# Generate srtm_continent_map.hpp from terrain.ardupilot.org directory listings.
#
# Crawls the SRTM3 directory on the ArduPilot terrain server, discovers which
# continent subdirectory each .hgt.zip tile lives in, and emits a C++ header
# with a static constexpr uint8_t[116][360] lookup table.
#
# Usage:
#   ./generate_srtm_continent_map.sh              # writes to default location
#   ./generate_srtm_continent_map.sh output.hpp   # writes to custom path
#
# Requires: curl, grep, sed, awk
#
# This script only needs to be run once.  The SRTM dataset was collected
# in 2000 and the server layout has not changed since.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PKG_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
# Default output: alongside plugin sources (private header, not installed)
OUTPUT="${1:-${PKG_DIR}/src/plugins/srtm_continent_map.hpp}"
SERVER="terrain.ardupilot.org"
SOURCE="SRTM3"
BASE_URL="https://${SERVER}/${SOURCE}"

CONTINENTS=(Africa Australia Eurasia Islands North_America South_America)

if [ -f "$OUTPUT" ] && grep -q 'static constexpr uint8_t MAP' "$OUTPUT" 2>/dev/null; then
  echo "SRTM continent map already exists, skipping"
  exit 0
fi

for cmd in curl grep sed awk; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Error: '$cmd' is required but not found" >&2
    exit 1
  fi
done

echo "Generating SRTM continent map"
echo "  server:  ${BASE_URL}"
echo "  output:  ${OUTPUT}"

fetch_tiles() {
  for i in "${!CONTINENTS[@]}"; do
    continent="${CONTINENTS[$i]}"
    printf "  Scanning %-15s" "${continent} ..." >&2

    html=$(curl -sfL "${BASE_URL}/${continent}/" 2>/dev/null) || {
      echo " FAILED (curl error)" >&2
      continue
    }

    count=0
    while IFS= read -r tile; do
      ns="${tile:0:1}"
      lat="${tile:1:2}"
      ew="${tile:3:1}"
      lon="${tile:4:3}"

      lat=$((10#$lat))
      lon=$((10#$lon))
      [ "$ns" = "S" ] && lat=$((-lat))
      [ "$ew" = "W" ] && lon=$((-lon))

      echo "$i $lat $lon"
      count=$((count + 1))
    done < <(
      echo "$html" |
        grep -o 'href="[NS][0-9][0-9][EW][0-9][0-9][0-9]\.hgt\.zip"' |
        sed 's/href="//; s/\.hgt\.zip"//'
    )

    printf " %d tiles\n" "$count" >&2
  done
}

fetch_tiles | awk -v output="$OUTPUT" '
BEGIN {
  LAT_MIN = -56;  LAT_MAX = 59
  LON_MIN = -180; LON_MAX = 179
  LAT_RANGE = LAT_MAX - LAT_MIN + 1
  LON_RANGE = LON_MAX - LON_MIN + 1

  for (i = 0; i < LAT_RANGE; i++)
    for (j = 0; j < LON_RANGE; j++)
      grid[i, j] = 255

  n = split("Africa/ Australia/ Eurasia/ Islands/ North_America/ South_America/", continents, " ")
  total = 0
}

{
  ci = $1; lat = $2; lon = $3
  li = lat - LAT_MIN
  lo = lon - LON_MIN
  if (li >= 0 && li < LAT_RANGE && lo >= 0 && lo < LON_RANGE) {
    grid[li, lo] = ci
    total++
  }
}

END {
  if (total < 10000) {
    printf "ERROR: only %d tiles found (expected ~14000) \342\200\224 server may be down\n", total > "/dev/stderr"
    exit 1
  }
  printf "  Total tiles: %d\n", total > "/dev/stderr"

  print "// Auto-generated by generate_srtm_continent_map.sh \342\200\224 DO NOT EDIT" > output
  print "#pragma once"                                       >> output
  print ""                                                   >> output
  print "#include <cstdint>"                                 >> output
  print "#include <optional>"                                >> output
  print "#include <string>"                                  >> output
  print ""                                                   >> output
  print "namespace mavros::extra_plugins::srtm"              >> output
  print "{"                                                  >> output
  print ""                                                   >> output
  printf "static constexpr int LAT_MIN = %d;\n",  LAT_MIN   >> output
  printf "static constexpr int LAT_MAX = %d;\n",  LAT_MAX   >> output
  printf "static constexpr int LON_MIN = %d;\n",  LON_MIN   >> output
  printf "static constexpr int LON_MAX = %d;\n",  LON_MAX   >> output
  printf "static constexpr int LAT_RANGE = %d;\n", LAT_RANGE >> output
  printf "static constexpr int LON_RANGE = %d;\n", LON_RANGE >> output
  print "static constexpr uint8_t SRTM_NO_DATA = 0xFF;"      >> output
  print ""                                                   >> output

  print "static constexpr const char * CONTINENTS[] = {"     >> output
  for (c = 1; c <= n; c++)
    printf "  \"%s\",\n", continents[c]                      >> output
  print "};"                                                 >> output
  print ""                                                   >> output

  printf "static constexpr uint8_t MAP[%d][%d] = {\n", LAT_RANGE, LON_RANGE >> output
  for (i = 0; i < LAT_RANGE; i++) {
    printf "  // lat %+d\n", LAT_MIN + i                     >> output
    printf "  {"                                             >> output
    for (j = 0; j < LON_RANGE; j++) {
      if (j > 0) printf ", "                                 >> output
      printf "0x%02X", grid[i, j]                            >> output
    }
    print "},"                                               >> output
  }
  print "};"                                                 >> output
  print ""                                                   >> output

  print "static inline std::optional<std::string> lookup_continent(int lat, int lon)" >> output
  print "{"                                                  >> output
  print "  if (lat < LAT_MIN || lat > LAT_MAX || lon < LON_MIN || lon > LON_MAX) {" >> output
  print "    return std::nullopt;"                           >> output
  print "  }"                                                >> output
  print "  uint8_t idx = MAP[lat - LAT_MIN][lon - LON_MIN];" >> output
  print "  if (idx == SRTM_NO_DATA) {"                        >> output
  print "    return std::nullopt;"                           >> output
  print "  }"                                                >> output
  print "  return std::string(CONTINENTS[idx]);"             >> output
  print "}"                                                  >> output
  print ""                                                   >> output
  print "}  // namespace mavros::extra_plugins::srtm"        >> output

  printf "  Wrote %s\n", output > "/dev/stderr"
}'
