#!/usr/bin/env python3
"""Generate srtm_continent_map.py from terrain.ardupilot.org directory listings.

Crawls the SRTM3 directory on the ArduPilot terrain server, discovers which
continent subdirectory each .hgt.zip tile lives in, and emits a Python module
with a zlib-compressed lookup table.

Usage:
    python generate_srtm_continent_map.py                 # default output path
    python generate_srtm_continent_map.py output.py       # custom output path

Requires only the standard library (urllib, re, zlib, base64).

This script only needs to be run once.  The SRTM dataset was collected
in 2000 and the server layout has not changed since.
"""

from __future__ import annotations

import base64
import re
import sys
import urllib.request
import zlib
from pathlib import Path

SERVER = "terrain.ardupilot.org"
SOURCE = "SRTM3"
BASE_URL = f"https://{SERVER}/{SOURCE}"

CONTINENTS = [
    "Africa",
    "Australia",
    "Eurasia",
    "Islands",
    "North_America",
    "South_America",
]

LAT_MIN, LAT_MAX = -56, 59
LON_MIN, LON_MAX = -180, 179
LAT_RANGE = LAT_MAX - LAT_MIN + 1  # 116
LON_RANGE = LON_MAX - LON_MIN + 1  # 360
NO_DATA = 0xFF

_TILE_RE = re.compile(r'href="([NS]\d{2}[EW]\d{3})\.hgt\.zip"')


def _fetch_tile_map() -> bytearray:
    """Crawl the server and build a flat lat×lon → continent-index map."""
    grid = bytearray([NO_DATA] * (LAT_RANGE * LON_RANGE))
    total = 0

    for ci, continent in enumerate(CONTINENTS):
        url = f"{BASE_URL}/{continent}/"
        print(f"  Scanning {continent:15s} ... ", end="", flush=True)

        try:
            with urllib.request.urlopen(url, timeout=120) as resp:
                html = resp.read().decode("utf-8", errors="replace")
        except Exception as e:
            print(f"FAILED ({e})")
            continue

        count = 0
        for match in _TILE_RE.finditer(html):
            name = match.group(1)
            lat = int(name[1:3]) * (-1 if name[0] == "S" else 1)
            lon = int(name[4:7]) * (-1 if name[3] == "W" else 1)

            li = lat - LAT_MIN
            lo = lon - LON_MIN
            if 0 <= li < LAT_RANGE and 0 <= lo < LON_RANGE:
                grid[li * LON_RANGE + lo] = ci
                count += 1
                total += 1

        print(f"{count} tiles")

    if total < 10000:
        print(
            f"ERROR: only {total} tiles found (expected ~14000) — server may be down",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"  Total tiles: {total}")
    return grid


def _format_data_literal(grid: bytearray) -> str:
    """Compress the grid and return indented, concatenated string literals."""
    compressed = zlib.compress(bytes(grid), level=9)
    encoded = base64.b64encode(compressed).decode("ascii")
    lines = [encoded[i : i + 76] for i in range(0, len(encoded), 76)]
    return "\n".join(f'    "{line}"' for line in lines)


_MODULE_TEMPLATE = '''\
"""Auto-generated SRTM continent lookup table.

Maps each 1-degree tile to its continent directory on terrain.ardupilot.org.
Generated by tools/generate_srtm_continent_map.py -- DO NOT EDIT.
"""

from __future__ import annotations

import base64
import zlib

_CONTINENTS = (
    "Africa/",
    "Australia/",
    "Eurasia/",
    "Islands/",
    "North_America/",
    "South_America/",
)

_LAT_MIN = {lat_min}
_LAT_RANGE = {lat_range}
_LON_MIN = {lon_min}
_LON_RANGE = {lon_range}
_NO_DATA = 0xFF

_MAP: bytes = zlib.decompress(base64.b64decode(
{data_literal}
))


def lookup_continent(lat: int, lon: int) -> str | None:
    """Return the continent directory for a 1-degree tile, or None if unavailable."""
    li = lat - _LAT_MIN
    lo = lon - _LON_MIN
    if not (0 <= li < _LAT_RANGE and 0 <= lo < _LON_RANGE):
        return None
    idx = _MAP[li * _LON_RANGE + lo]
    if idx == _NO_DATA:
        return None
    return _CONTINENTS[idx]
'''


def _write_module(grid: bytearray, output: Path) -> None:
    data_literal = _format_data_literal(grid)
    content = _MODULE_TEMPLATE.format(
        lat_min=LAT_MIN,
        lat_range=LAT_RANGE,
        lon_min=LON_MIN,
        lon_range=LON_RANGE,
        data_literal=data_literal,
    )
    output.write_text(content)
    print(f"  Wrote {output}")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    pkg_dir = script_dir.parent
    default_output = pkg_dir / "mavros_extras" / "srtm_continent_map.py"
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else default_output

    if output.exists():
        print(f"SRTM continent map already exists at {output}")
        print("  Delete the file to regenerate.")
        return

    print("Generating SRTM continent map")
    print(f"  server:  {BASE_URL}")
    print(f"  output:  {output}")

    grid = _fetch_tile_map()
    _write_module(grid, output)


if __name__ == "__main__":
    main()
