[options.entry_points]
console_scripts =
    terrain_server=mavros_extras.terrain_server.cli:main

[develop]
script_dir=$base/lib/mavros_extras

[install]
install_scripts=$base/lib/mavros_extras

[flake8]
# NOTE: based on ament_flake8.ini from Jazzy, but extended with Q000,I100,I101
extend-ignore = B902,C816,D100,D101,D102,D103,D104,D105,D106,D107,D203,D212,D404,I202,Q000,I100,I101
import-order-style = google
max-line-length = 99
show-source = true
statistics = true
