"""Auto-generated SRTM continent lookup table.

Maps each 1-degree tile to its continent directory on terrain.ardupilot.org.
Generated by tools/generate_srtm_continent_map.py -- DO NOT EDIT.
"""

from __future__ import annotations

import base64
import zlib

_CONTINENTS = (
    "Africa/",
    "Australia/",
    "Eurasia/",
    "Islands/",
    "North_America/",
    "South_America/",
)

_LAT_MIN = -56
_LAT_RANGE = 116
_LON_MIN = -180
_LON_RANGE = 360
_NO_DATA = 0xFF

_MAP: bytes = zlib.decompress(base64.b64decode(
    "eNrtnIt24jAMRG3F/v9P1nZJSPyQ35JtaHV2OSXQUG6G8VgOQZxX9lWFJx344bX6Ddinkn/iT33G"
    "m9n3TysxPjnPJfLxn50S5gr/+ALprTiOMWeLfyXozue973fRRaZka/x5qjcf33RUW9LGl42Bi/X8"
    "e3zZPZTHfM4rBHsscMvjWPGqa/V8LJFzAHoK9V/pGws4fzVo/VM1ip7M2f4Szks82n4vaJ3kvELS"
    "g5z3bfroDGdcy9l+l5wxzXm+om1Ym6QCDjGnMc9XtB0BfWzKWTv1DZw3NowC58WJ49MwExx1UEnO"
    "uJYzI2t1lWyk8GFqXQN6ImWLVhi0ekqas27kvKKsFGilpElHQDVVa0byOs6Wm7OS55ys87l/nIUx"
    "byJoKwRaKWnQXZyXNQqsDGilpEHrKZwrBlL9x3la4tBpvKLGob6Ts97NOJTKkebArtfoWXfTtlaA"
    "tMqB5pG3OGftANWnUUvoeYj1Ppw7ncD/RY3jnworATrNWb0fnMPZZ3lueRjqOFC8kOqoXTVuPxKc"
    "VVnP1x0lzflC+/xKoOYIYLBB14U7Rs4NXa4WzrKkXTlf4H2koeR9qOczZnC2fHJWSIC+OCsR1L4N"
    "a4/j03x6HqIMmyu18HNWKg+aN1BXD4GXcjUibSLxfu9lc3nKPaBVrvj7/xlvJjJFFeb3cZql5SrO"
    "RxNnArSS4ozUupafPejIpj0/11Mw83N2DFoJCDon1jhvOMjJ/WKc82Qwsxq059FsM+E4MVdyDmKb"
    "UMtpHWeFvJ0l7ZxNkBEoUxKWwSwyEP6/adsnFFvEPufSRNtbJSfUrD+AMxY498xPAMvkCM7PlmK7"
    "LZj5aSbm1q4R9JMxVFfYADKBRWEimmHE+UPHu/z5CSDaCDCHs+XH3OEcBHJ4IYAQxLkdrnpviY4S"
    "kEcuhjoNMydoHs8DstyHXMzOoz34AFdyPkb0HJhHy5tyuV44b7YI/uPub7CqVIZyq56rOasO7YAP"
    "+nX75osQaZ2wlSJmWMWZfZqCqa5oQWU334etL+TYUs5dQpIlUI68hjPO41w18DkxIPLlSMq34NPi"
    "jUAvEfT5dCbMoVWoZsyeIQdjHj0oyg50q8KzUk2gu0JGFCooygAZyqKj4ENNan5SgbkbdEQ5Cfr0"
    "FIA0zTR/Xs4i/f27QTTEGUqcY+S+1nP7gWs7iFpGA+fOVxgXdE6CSQmjEzuqPhmybm3rHRq7QSs1"
    "RrqNMzqirrYCac71Q+HAftUY6AQDWsBPz6dezAWUvJStGGelxkCXOCPVswDIIGrSM7eY84Juo/pM"
    "oFVDtXN+EGMQ29ztI1kZeAmXjKNPvG2YS5yBCGJ+HPZTXC5iXBnjvoWpE5Zxy1BDleXsB9ynQURq"
    "3DEQnxhg0H5O9DOmTwdxGuVGzvHcAtwOR8z53deAgCxITrMlMA9zVpm+TugQjybBGfOcEdGjCG/Z"
    "3r1S/xOwmPJkzKquLedAjZJyPAsMjgTxkWDHbJq7HHMx06CduTRhG37IcONe1Wh2zWumyTmSNp7/"
    "JmHGzHcnSM4QcAbPTSrRvdtLU13DuxvPyqXlfO8ks2ZC+HMs3wbO8t1mUr65LtN6d44dl+ac7ORP"
    "CxXZARBJzlV82dxZVXPGtJ7TKyYrGvxojPn//654lDTJcTPUMRvnlEFToKM2nZvUxu3hYIJsfMj0"
    "s+rkzChoknQqq4ULJkXOk52DoGxujZ8/Z/lTtjHAuXjBiLQ7JJTOvwJVrW5zy9OYlJpNncyZx8Hi"
    "hQxIoHHzWZJz29XATADzfY/wa8E2c7N1ZE6ZC1vQeX+AXvg9F12LMb+pDjDmlbMHmj4Ngz7FyGt3"
    "RiQ77bnvQo2hZM8fna29oBVrZTDnSmK4a4f8Cm8+Z+ObCfbrGRnl/HCG1uLkfPwf/jrynZ+YY5nj"
    "gG3IcIb24msL9SRoU8rMZsyde0Ejr5ojCyGHO6hj3DlTKYS2UcpdoDG1ZYiwe3bB7LmgCefZtJ4n"
    "c06Ch3EpJ1KH7IzbGJOfhZyHYYwxY+YAZtDVTeaRC+camrNx11g20LJ7nAD4FS3fz0hwfjp1455x"
    "wmaL0RycveXWNZ2joo10KZpxvsLDGWBDzobnpTrCshDn6Gy7NZRL7TnTJWcsr7WqimPCJOfs6V8r"
    "tMwg6WwfulX8DGrGqMm0D2cjZR1hAiw5zDBnSK8DbICZBzQ9SYuWSUGqnFeZBtpIc06uMiHdIJ5S"
    "DmecwtnIc1b51WnyG3wFPuOcYwvZjLMZgxx8qf0OVXUYWfSO/peP80vgyzCbJscocPb67vUfd04x"
    "zwFtjDHy1pECfZ8GV80P+QfEKa0O01lsaePyjUqM7MOkyxn248wX6rz5ApG9goFTNOUJatp0C/p9"
    "3gFLeCa0TOYT4TgtB9oMFhomXaeyBUq6xjzQZrjEOMOkKYv3fUIp1Byc+3DDVuV8cVOEdL0Z88oa"
    "diuv5w97ydndw4djDjtZm5lG59Kh4JDGImhW0IavPtyc415/2qNb32+V6UpwnpwkumbhKdLeucpV"
    "b9uw1sCs+1M4x6ck17xxswdn3JZztMHkMG4o5+S1afdJG96aT6mVdwdfvm4o9yBIbtjAMvw/KT0i"
    "Fkl3CpZt2p1uFMFKzpBeW6ODRAiUa+WVYRpI6HlZUyOr6Opl8BSNAe/laiLl3BmXD4OBgTUHip7I"
    "nN4nHWsq0QfnuG2apUnS/wAuHod9"
))


def lookup_continent(lat: int, lon: int) -> str | None:
    """Return the continent directory for a 1-degree tile, or None if unavailable."""
    li = lat - _LAT_MIN
    lo = lon - _LON_MIN
    if not (0 <= li < _LAT_RANGE and 0 <= lo < _LON_RANGE):
        return None
    idx = _MAP[li * _LON_RANGE + lo]
    if idx == _NO_DATA:
        return None
    return _CONTINENTS[idx]
