"""Auto-generated SRTM continent lookup table.

Maps each 1-degree tile to its continent directory on terrain.ardupilot.org.
Generated by ../../tools/generate_srtm_continent_map.py -- DO NOT EDIT.
"""

from __future__ import annotations

import zlib

_CONTINENTS = (
    'Africa/',
    'Australia/',
    'Eurasia/',
    'Islands/',
    'North_America/',
    'South_America/',
)

_LAT_MIN = -56
_LAT_RANGE = 116
_LON_MIN = -180
_LON_RANGE = 360
_NO_DATA = 0xFF

# Zlib-compressed 116x360 grid: each byte is a continent index (0-5) or 0xFF.
# Inspect with: python -c "import zlib; print(zlib.decompress(bytes.fromhex('<hex>')).hex())"
_MAP: bytes = zlib.decompress(
    bytes.fromhex(
        '78daed9c8b76e2300c446dc5feff4fd6764948fc90df926d6875763925d0506e86f1580e419c57'
        'f65585271df8e1b5fa0dd8a7927fe24f7dc69bd9f74f2b313e39cf25f2f19f9d12e60afff802e9'
        'ad388e31678b7f25e8cee7bdef77d145a6646bfc79aa371fdf74545bd2c6978d818bf5fc7b7cd9'
        '3d94c77cce2b047b2c70cbe358f1aa6bf57c2c9173007a0af55fe91b0b387f3568fd53358a9ecc'
        'd9fe12ce4b3cda7e2f689de4bc42d2839cf76dfae80c675ccbd97e979c31cd79bea26d589ba402'
        '0e31a731cf57b41d017d6cca593bf50d9c37368c02e7c589e3d330131c755049ceb89633236b75'
        '956ca4f0616a5d037a22658b5618b47a4a9ab36ee4bca2ac1468a5a449474035556b46f23ace96'
        '9bb392e79cacf3b97f9c85316f22682b045a2969d05d9c97350aac0c68a5a441eb299c2b0652fd'
        'c7795ae2d069bca2c6a1be93b3decd3894ca91e6c0aed7e85977d3b65680b4ca81e691b73867ed'
        '00d5a7514be87988f53e9c3b9dc0ff458de39f0a2b013acd59bd1f9cc3d967796e7918ea3850bc'
        '90eaa85d356e3f129c5559cfd71d25cdf942fbfc4aa0e60860b041d7853b46ce0d5dae16ceb2a4'
        '5d395fe07da4a1e47da8e7336670b67c72564880be382b11d4be0d6b8fe3d37c7a1ea20c9b2bb5'
        'f073562a0f9a3750570f81977235226d22f17eef657379ca3da055aef8fbff196f26324515e6f7'
        '719aa5e52ace47136702b492e28cd4ba969f3de8c8a63d3fd75330f373760c5a09083a27d6386f'
        '38c8c9fd629cf36430b31ab4e7d16c33e1383157720e629b50cb691d6785bc9d25ed9c4d901128'
        '531296c12c3210febf69db27145bc43ee7d244db5b2527d4ac3f80331638f7cc4f00cbe408cecf'
        '9662bb2d98f96926e6d6ae11f493315457d80032814561229a61c4f943c7bbfcf90920da083087'
        'b3e5c7dce11c047278218010c4b91dae7a6f898e1290472e863a0d3327681ecf03b2dc875cccce'
        'a33df80057723e46f41c9847cb9b72b95e386fb608fee3ee6fb0aa548672ab9eab39ab0eed800f'
        'fa75fbe68b10699db095226658c5997d9a82a9ae68416537df87ad2fe4d852ce5d429225508ebc'
        '8633cee35c35f0393120f2e548cab7e0d3e28d402f11f4f97426cca155a866cc9e2107631e3d28'
        'ca0e74abc2b3524da0bb4246142a28ca0019caa2a3e0434d6a7e5281b91b74443909faf4148034'
        'cd347f5ece22fdfdbb4134c4194a9c63e4bed673fb816b3b885a4603e7ce571817744e824909a3'
        '133baa3e19b26e6deb1d1abb412b3546ba8d333aa2aeb60269cef543e1c07ed518e804035ac04f'
        'cfa75ecc0594bc94ad1867a5c640973823d5b300c8206ad233b798f3826ea3fa4ca05543b5737e'
        '106310dbdced2359197809978ca34fbc6d984b9c8108627e1cf6535c2e625c19e3be85a9139671'
        'cb504395e5ec07dca741446adc31109f1860d07e4ef433a64f07711ae546cef1dc02dc0e47ccf9'
        'ddd780802c484eb325300f735699be4ee8108f26c119f39c11d1a3086fd9debd52ff13b098f264'
        'ccaaae2de7408d92723c0b0c8e04f19160c76c9abb1c7331d3a09db934611b7ec870e35ed56876'
        'cd6ba6c93992369eff2661c6cc772748ce107006cf4d2ad1bddb4b535dc3bb1bcfcaa5e57cef24'
        'b36642f8732cdf06cef2dd6652beb92ed37a778e1d97e69cece44f0b15d9011049ce557cd9dc59'
        '5573c6b49ed32b262b1afc688cf9ffffae789434c97133d4311be7944153a0a3369d9bd4c6ede1'
        '60826c7cc8f4b3eae4cc286892742aab850b2645ce939d83a06c6e8d9f3f67f953b631c0b978c1'
        '88b43b2494cebf0255ad6e73cbd398949a4d9dcc99c7c1e2850c48a071f3599273dbd5c04c00f3'
        '7d8ff06bc13673b375644e990b5bd0797f805ef83d175d8b31bfa90e30e695b3079a3e0d833ec5'
        'c86b7746243bedb9ef428da164cf1f9dadbda0156b6530e74a62b86b87fc0a6f3e67e39b09f6eb'
        '1919e5fc7086d6e2e47cfc1ffe3af29d9f986399e3806dc87086f6e26b0bf5246853cacc66cc9d'
        '7b4123af9a230b21873ba863dc39532984b651ca5da031b56588b07b76c1ecb9a009e7d9b49e27'
        '734e82877129275287ec8cdb18939f859c87618c3163e60066d0d54de6910be71a9ab371d75836'
        'd0b27b9c00f8152ddfcf48707e3a75e39e71c2668bd11c9cbde5d6359da3a28d74299a71bec2c3'
        '196043ce86e7a53ac2b210e7e86cbb35944bed39d325672cafb5aa8a63c224e7ece95f2bb4cc20'
        'e96c1fba55fc0c6ac6a8c9b40f6723651d61022c39cc306748af036c809907343d498b964941aa'
        '9c579906da48734eae3221dd209e520e679cc2d9c87356f9d569f21b7c053ee39c630bd98cb319'
        '831c7ca9fd0e55751859f48efe978ff34be0cb309b26c72870f6faeef51f774e31cf016d8c31f2'
        'd691027d9f0657cd0ff907c429ad0ed3596c69e3f28d4a8cecc3a4cb19f6e3cc17eabcf90291bd'
        '82815334e5096ada740bfa7dde014b7826b44ce613e1382d07da0c161a265da7b2054abac63cd0'
        '66b8c438c3a4298bf77d4229d41c9cfb70c356e57c71538474bd19f3ca1a762bafe70f7bc9d9dd'
        'c387630e3b599b9946e7d2a1e090c6226856d086af3edc9ce35e7fdaa35bdf6f95e94a709e9c24'
        'ba66e129d2deb9ca556fdbb0d6c0acfb5338c7a724d7bc71b30767dc9673b4c1e4306e28e7e4b5'
        '69f7491bde9a4fa99577075fbe6e28f720486ed8c032fc3f293d221649770a966dda9d6e14c14a'
        'ce905e5ba3834408946be595611a48e879595323abe8ea65f0148d01efe56a22e5dc19970f8381'
        '8135078a9ec89cde271d6b2ad107e7b86d9aa549d2ff002e1e877d'
    )
)


def lookup_continent(lat: int, lon: int) -> str | None:
    """Return the continent directory for a 1-degree tile, or None if unavailable."""
    li = lat - _LAT_MIN
    lo = lon - _LON_MIN
    if not (0 <= li < _LAT_RANGE and 0 <= lo < _LON_RANGE):
        return None
    idx = _MAP[li * _LON_RANGE + lo]
    if idx == _NO_DATA:
        return None
    return _CONTINENTS[idx]
