# goal

# if parent and child frame are provided, target_pose will be ignored
string parent_frame
string target_frame

geometry_msgs/PoseStamped target_pose

# set timeout to negative value for infinite duration
float32 timeout

float32 position_tolerance
float32 heading_tolerance
float32 min_success_duration

---
# result

uint8 SUCCESS = 0
uint8 TIMEOUT = 1
uint8 CANCELLED = 2
uint8 WRONG_MODE = 3
uint8 error_code

---
# feedback
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
float32 distance_remaining