---

name: CI

on:
  push:
    branches: [master, ros2]
  pull_request:
    branches: [master, ros2]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  industrial_ci:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        env:
          # - {ROS_DISTRO: foxy, ROS_REPO: testing}
          # - {ROS_DISTRO: foxy, ROS_REPO: main}
          # - {ROS_DISTRO: galactic, ROS_REPO: testing}
          # - {ROS_DISTRO: galactic, ROS_REPO: main}
          - {ROS_DISTRO: humble, ROS_REPO: main}
          # - {ROS_DISTRO: iron, ROS_REPO: main}
          - {ROS_DISTRO: jazzy, ROS_REPO: main}
          - {ROS_DISTRO: kilted, ROS_REPO: main}
          - {ROS_DISTRO: rolling, ROS_REPO: testing}
    env:
      CCACHE_DIR: /github/home/.ccache
      AFTER_INSTALL_TARGET_DEPENDENCIES: ./mavros/scripts/install_geographiclib_datasets.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: "${{ env.CCACHE_DIR }}"
          key: "ccache-${{ runner.os }}-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{ hashFiles('**/package.xml', '**/CMakeLists.txt') }}"
          restore-keys: |
            ccache-${{ runner.os }}-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-
      - uses: 'ros-industrial/industrial_ci@master'  # nosemgrep
        env: ${{matrix.env}}
